// Package startup manages the systemd user unit. It does not start/stop the
// running daemon or change linger; those remain explicit user operations.
package startup

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const UnitName = "akid.service"
const marker = "# Generated by akid startup; managed file.\n"

type Runner func(context.Context, string, ...string) (string, error)

type Service struct {
	ConfigHome string
	Executable string
	StateHome  string
	RuntimeDir string
	Run        Runner
}

func RunCommand(ctx context.Context, name string, args ...string) (string, error) {
	data, err := exec.CommandContext(ctx, name, args...).CombinedOutput()
	if err != nil {
		return string(data), fmt.Errorf("%s %s: %w: %s", name, strings.Join(args, " "), err, strings.TrimSpace(string(data)))
	}
	return string(data), nil
}

func (s Service) Path() string { return filepath.Join(s.ConfigHome, "systemd", "user", UnitName) }

func (s Service) Unit() ([]byte, error) {
	for _, path := range []string{s.ConfigHome, s.Executable, s.StateHome} {
		if !filepath.IsAbs(path) || strings.ContainsAny(path, "\x00\n\r") {
			return nil, errors.New("systemd paths must be absolute and contain no NUL or newlines")
		}
	}
	if s.RuntimeDir != "" && (!filepath.IsAbs(s.RuntimeDir) || strings.ContainsAny(s.RuntimeDir, "\x00\n\r")) {
		return nil, errors.New("runtime directory must be absolute and contain no NUL or newlines")
	}
	var unit strings.Builder
	unit.WriteString(marker + "[Unit]\nDescription=akid process supervisor\n\n[Service]\nType=simple\n")
	fmt.Fprintf(&unit, "ExecStart=%s daemon run\n", quote(s.Executable, true))
	fmt.Fprintf(&unit, "Environment=%s\n", quote("XDG_STATE_HOME="+s.StateHome, false))
	// Also preserve an unset runtime directory; otherwise systemd's inherited
	// value would move the socket away from the installing CLI's fallback.
	fmt.Fprintf(&unit, "Environment=%s\n", quote("XDG_RUNTIME_DIR="+s.RuntimeDir, false))
	unit.WriteString("Restart=on-failure\nRestartSec=2s\nKillMode=mixed\nTimeoutStopSec=75s\nUMask=0077\n\n[Install]\nWantedBy=default.target\n")
	return []byte(unit.String()), nil
}

func quote(value string, execLine bool) string {
	value = strings.NewReplacer("\\", "\\\\", "\"", "\\\"", "%", "%%", "\t", "\\t").Replace(value)
	if execLine {
		value = strings.ReplaceAll(value, "$", "$$")
	}
	return "\"" + value + "\""
}

func (s Service) managedFile() (bool, error) {
	info, err := os.Lstat(s.Path())
	if errors.Is(err, os.ErrNotExist) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	if !info.Mode().IsRegular() {
		return false, fmt.Errorf("refusing to replace non-regular unit %s", s.Path())
	}
	data, err := os.ReadFile(s.Path())
	if err != nil {
		return false, err
	}
	if !strings.HasPrefix(string(data), marker) {
		return false, fmt.Errorf("unit %s is not managed by akid", s.Path())
	}
	return true, nil
}

func (s Service) Install(ctx context.Context) error {
	unit, err := s.Unit()
	if err != nil {
		return err
	}
	if _, err := s.managedFile(); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(s.Path()), 0o700); err != nil {
		return err
	}
	file, err := os.CreateTemp(filepath.Dir(s.Path()), ".akid-unit-*")
	if err != nil {
		return err
	}
	defer os.Remove(file.Name())
	if _, err = file.Write(unit); err == nil {
		err = file.Sync()
	}
	closeErr := file.Close()
	if err != nil {
		return err
	}
	if closeErr != nil {
		return closeErr
	}
	if err := os.Rename(file.Name(), s.Path()); err != nil {
		return err
	}
	if _, err := s.Run(ctx, "systemctl", "--user", "daemon-reload"); err != nil {
		return err
	}
	_, err = s.Run(ctx, "systemctl", "--user", "enable", UnitName)
	return err
}

func (s Service) Uninstall(ctx context.Context) error {
	exists, err := s.managedFile()
	if err != nil {
		return err
	}
	if !exists {
		return nil
	}
	if _, err := s.Run(ctx, "systemctl", "--user", "disable", UnitName); err != nil {
		return err
	}
	if err := os.Remove(s.Path()); err != nil {
		return err
	}
	_, err = s.Run(ctx, "systemctl", "--user", "daemon-reload")
	return err
}

func (s Service) Linger(ctx context.Context, uid string) (bool, error) {
	value, err := s.Run(ctx, "loginctl", "show-user", uid, "--property=Linger", "--value")
	if err != nil {
		return false, err
	}
	value = strings.TrimSpace(value)
	if value != "yes" && value != "no" {
		return false, fmt.Errorf("unexpected linger value %q", value)
	}
	return value == "yes", nil
}
